iterator and generator similar to range were created
femtokot/iterators pull request #1
Opened 2019-02-26 20:58 UTC by femtokot

2019-03-09 15:34 UTC, AleksandrSl requested changes
И тестов еще нет

2019-03-09 15:34 UTC, AleksandrSl commented on iterator.py
> +            while self.n > self.stop:
Здесь не нужен while, так как цикл всегда прерывается на return, нужно просто условие

2019-03-09 15:34 UTC, AleksandrSl commented on iterator.py
> +        self.n = self.start
Можно пологичнее имена выбрать, как в генераторе, например

2019-03-12 15:55 UTC, femtokot commented on iterator.py
> +            while self.n > self.stop:
Спасибо! убрала while

2019-03-12 15:56 UTC, femtokot commented on iterator.py
> +        self.n = self.start
имена изменены

2019-03-13 06:40 UTC, AleksandrSl requested changes

2019-03-13 06:40 UTC, AleksandrSl commented on iterator.py
> +                a = self.n
Вот тут забыла `n`

2019-03-20 07:30 UTC, AleksandrSl approved these changes

2019-05-23 13:02 UTC, merged